language: php

php:
  - 7.1

services:
  - docker

sudo: false

branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^\d+\.\d+?$/

cache:
  directories:
  - $HOME/.composer/cache

  env:
  global:
    - DMS_CORE_ADDRESS="http://127.0.0.1:8081/"

install:
  - cp env.travis .env
  - cp env.travis testing.env
  - travis_retry composer install --no-interaction

before_script:
  - phpenv config-rm xdebug.ini # disabling XDebug as currently we are not interested in code coverage report
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick # install imagemagick for thumbnail generation of files https://github.com/travis-ci/travis-ci/issues/781#issuecomment-332473065
  - sudo service mysql stop
  - docker-compose -f ./docker-compose.dev.example.yml up -d
  - php -f ./tests/wait.php

script: 
  - ./vendor/bin/parallel-lint --exclude vendor .
  - shellcheck ./docker/*.sh
  - php artisan view:clear
  - ./vendor/bin/php-cs-fixer fix --dry-run
  - mkdir ./storage/documents
  - composer run install-video-cli
  - chmod +x ./bin/bin/packager-linux
  - composer run install-content-cli
  - composer run install-language-cli
  - composer run install-streaming-client
  - php artisan config:clear
  - php artisan route:clear
  - php artisan migrate --env=testing --force
  - php artisan db:seed --env=testing --force
  - vendor/bin/phpunit

after_script:
  - docker-compose -f ./docker-compose.dev.example.yml down

notifications:
  email:
    on_success: never