##
## Example Docker Compose file
##
## This example shows how to expose the K-Box on localhost
## For more information please check ./docs/user/installation.md
##
## Lines that starts with "##" are comments, lines that starts
## with "#" are optional or advanced configurations, that can be
## uncommented if needed
##

version: '2'

networks:
  internal:

services:

  ## The Search Engine service
  engine:
    image: "klinktech/k-search-engine:1.0.1"
    volumes:
      - "./storage/index:/opt/solr/k-search/k-search/data"
    expose:
      - "8983"
    environment:
      ## the SOLR external address
      KLINK_SOLR_MYHOST: engine
    networks:
      - internal

  ## The Search Engine API
  ksearch:
    image: "klinktech/k-search:3.6.0-2"
    environment:
      ## Further datails about K-Search configuration in https://github.com/k-box/k-search
      ## Solr search configuration
      - SOLR_HOST=engine # this is the external address of Solr
      - SOLR_CORE=k-search # this is the Solr index name
      ## Registry configuration
      - KLINK_REGISTRY_ENABLED=0 # = no authentication
    depends_on:
      - engine
    networks:
      internal:
        aliases:
          ## the K-Box service checks the validity of the host, and just ksearch is not a valid host name
          - ksearch.local

  ## The database
  database:
    image: mariadb:10
    environment:
      MYSQL_DATABASE: dms
      MYSQL_USER: dms
      MYSQL_ROOT_PASSWORD: "2381aa6a99bee6ff61c2209ef4373887"
      MYSQL_PASSWORD: "b2510859c83414e0cbefd26284b9171d"
    networks:
      - internal
    volumes:
      - "./storage/database:/var/lib/mysql"

  ## The K-Box container
  kbox:
    image: "klinktech/k-box:0.27.2"
    environment:
      ## K-Box access
      KBOX_APP_URL: "http://localhost:8080/"
      # KBOX_APP_INTERNAL_URL: "http://kbox/" # Specify it only if the service name is different than kbox
      ## Administrator account
      ## uncomment the next two lines and write a password to automatically create that user at startup
      # KBOX_ADMIN_USERNAME: "admin@kbox.local"
      # KBOX_ADMIN_PASSWORD: ""
      ## Deploy configuration
      KBOX_DB_HOST: database # Host where the database is listening on
      KBOX_DB_NAME: dms  # must be the same as MYSQL_DATABASE
      KBOX_DB_USERNAME: dms  # must be the same as MYSQL_USER
      KBOX_DB_PASSWORD: "b2510859c83414e0cbefd26284b9171d"  # must be the same as MYSQL_PASSWORD
      KBOX_SEARCH_SERVICE_URL: "http://ksearch.local/"
    depends_on:
      - ksearch
      - database
    volumes:
      - "./storage/data:/var/www/dms/storage"
    ports:
      - "8080:80"
    networks:
      - internal
