name: CI

on: 
  push:
    branches: 
      - "master"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  phpunit:
    name: Tests PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    container: 
      image: klinktech/k-box-ci-pipeline-php:${{ matrix.php }}
      options: --user root 

    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_DATABASE: dms
          MYSQL_USER: dms
          MYSQL_ROOT_PASSWORD: "dms"
          MYSQL_PASSWORD: "dms"
          MYSQL_INITDB_SKIP_TZINFO: 1
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      engine:
        image: klinktech/k-search-engine:1.0.1
        env:
          KLINK_SOLR_MYHOST: engine
        ports:
          - 8983
      ksearch:
        image: klinktech/k-search:3.6.0-2
        env:
          SOLR_HOST: engine # this is the external address of Solr
          SOLR_CORE: k-search # this is the Solr index name
          KLINK_REGISTRY_ENABLED: 0 # = no authentication
        ports:
          - 8081

    strategy:
      fail-fast: true
      matrix:
        php: [7.2]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      
    - name: Prepare environment
      run: |
        cp env.ci .env
        cp env.ci .env.testing
        mkdir ./storage/documents
        composer install --prefer-dist
        composer run install-video-cli
        chmod +x ./bin/bin/packager-linux
        composer run install-content-cli
        composer run install-language-cli
        composer run install-streaming-client
        yarn
        yarn run production
        
    - name: Run Testsuite
      env:
        DMS_CORE_ADDRESS: http://ksearch:8081/
        KBOX_SEARCH_SERVICE_URL: http://ksearch:8081/
      run: |
        php artisan view:clear
        php artisan config:clear
        php artisan route:clear
        php artisan migrate --env=testing --seed --force
        vendor/bin/phpunit --verbose
